### ISSUE TITLE
Resizing while maintaining the ratio

### ISSUE THREAD

**Issue by timvanuum** [svgdotjs/svg.resize.js#10]
Hi there,

First of all great plugin. Works very easy.
But I have one question.
Is it possible to resize a element but keeping the ratio?

Thanks

**Comment by timvanuum** [comment]
Noticed that this works with an image. But not working perfectly. The selection can be resized without respecting ratio but the image itself keeps it's ratio.

**Comment by Fuzzyma** [comment]
It is not possible. However if would make a good feature. I will think
about it.
The only reason an image preserve it's aspect ratio is because the default
value of the preserveAspectRatio attribute is true. If you change it, it
will behave a normal rectangle.

Actually the image container always behaves like that - only the image
itself will fit the container or it will preserve the aspect ratio - as you
defined.

Tim van Uum <notifications@github.com> schrieb am Mi., 17.02.2016, 13:38:

**Comment by timvanuum** [comment]
Cool, for now this not really an issue for me but would be nice if this is a feature. For me it's just about the image resizing so for now I can deal with only the selection that doesn't respect the ratio.

**Comment by rkbrewer** [comment]
+1! Great plugin. I'd love to be able to lock the aspect-ratio too while resizing.

**Comment by rkbrewer** [comment]
This was actually pretty easy. The quick and dirty hack is to edit ResizeHandler.prototype.update. Change `diffY`'s assignment to be equal to `diffX / someAspectRatio`.

If you like @Fuzzyma I can create a PR that applies this logic conditionally if someone instantiates the resize with a new option of `aspectRatio`.

**Comment by rkbrewer** [comment]
UPDATE: that fix only works when manipulating the TopLeft and BottomRight control points.  (I'm hiding all but the bottom-right control point via CSS.)

Hope that helps someone.  I'll hold off on that PR @Fuzzyma . Thanks again for the awesome plugin!

**Comment by jkevingutierrez** [comment]
+1

**Comment by Fuzzyma** [comment]
so the question is: when to allow forced aspect ratios? Only at the corners? Or at the edges, too?
Its after all not that easy to implement because the resizing algo works with differences only and not with absolute values of width and height. I wonder why I made this decision back then...

**Comment by rafaelsantosferraz** [comment]
To maintain the ratio diffX and diffY need to be the same in abs values, right? So before passing there values foward, I test then and make then equal to the higher diff. The only important thing is to remeber direction.  


```
// Left-Top-Edge
        case 'lt':
                // We build a calculating function for every case which gives us the new position of the this.el
                this.calc = function (diffX, diffY) {
                    // The procedure is always the same
                    // First we snap the edge to the given grid (snapping to 1px grid is normal resizing)

                    if(Math.abs(diffX) > Math.abs(diffY)){
                        diffY =  diffX;
                    } else {
                       diffX = diffY;
                    }

                    var snap = this.snapToGrid(diffX, diffY);


...

// Right-Top
            case 'rt':
                // s.a.
                this.calc = function (diffX, diffY) {

                    if(Math.abs(diffX) > Math.abs(diffY)){
                        diffY = -diffX;
                    } else {
                       diffX = -diffY;
                    }

                    var snap = this.snapToGrid(diffX, diffY, 1 << 1);

...

// Right-Bottom
            case 'rb':
                // s.a.
                this.calc = function (diffX, diffY) {

                    if(Math.abs(diffX) > Math.abs(diffY)){
                        diffY = diffX;
                    } else {
                       diffX = diffY;
                    }

                    var snap = this.snapToGrid(diffX, diffY, 0);

...

// Left-Bottom
            case 'lb':
                // s.a.
                this.calc = function (diffX, diffY) {

                    if(Math.abs(diffX) > Math.abs(diffY)){
                        diffY =  -diffX;
                    } else {
                       diffX = -diffY;
                    }
                    var snap = this.snapToGrid(diffX, diffY, 1);
```
