### ISSUE TITLE
Possible to tell which point is being resized in a polyline?

### ISSUE THREAD

**Issue by ianneub** [svgdotjs/svg.resize.js#31]
Hello,

Awesome work on svgjs and plugins! Thanks for making them.

Hopefully quick question: is it possible to tell in the `resizing` or `resizedone` event which point is being moved?

Alternatively is it possible to disable moving a single point in a polyline?

Thank you for your help!

**Comment by Fuzzyma** [comment]
No unfortunately this is not possible. I assume it would be a bit hackish to add. But I am open to any suggestions!

**Comment by ianneub** [comment]
Thank you, I'll poke around the code and see what I can do.
