### ISSUE TITLE
Current version is not compatible

### ISSUE THREAD

**Issue by Yarisrespect** [svgdotjs/svg.resize.js#32]
svg.resize now is not compatible with latest svg.select.js

**Comment by Fuzzyma** [comment]
Can you elaborate further?

**Comment by Yarisrespect** [comment]
"dependencies": {
    "svg.js":"^2.0.2",
    "svg.select.js":"^1.0.4"
}
Composer found a version conflict with svg.select.js 2.**

**Comment by Fuzzyma** [comment]
the new release fixed that. Thanks for reporting!
