### ISSUE TITLE
stop propagation 

### ISSUE THREAD

**Issue by ElMaghri** [svgdotjs/svg.resize.js#35]
hello,

i have installed the svg.resize.js plugin for resizement. It works very good but i want to add Zoom effect (using svg.panzoom.js).
The problem comes when i try to rotate or resize an object. In fact, the viewBox also changes with the mouse event.
So, how can i stop the propagation of the resize and rotation events.

**Comment by Fuzzyma** [comment]
What you want to stop propagating are the click events, right? svg.select.js catches them as well as the panZoom plugin. Hm maybe we should add calls to stopPropagation to prevent the event from bubbling

**Comment by ElMaghri** [comment]
![ezgif com-crop](https://user-images.githubusercontent.com/26650208/27798831-a5326b50-600a-11e7-8532-bba919b9d955.gif)

this the a screen of shoot when i try to rotate object ,panZoom catch the mouse event and move the viewBox i like to rotate and resize object without changing the viewBox

**Comment by Fuzzyma** [comment]
Try the following: In the unminified dist-file there are 3 sections looking similar to this:

```js
            return function (ev) {
                ev = ev || window.event;
                ev.preventDefault ? ev.preventDefault() : ev.returnValue = false;

                var x= ev.pageX || ev.touches[0].pageX;
                var y= ev.pageY || ev.touches[0].pageY;
                _this.el.fire(eventName, {x: x, y: y, event: ev});
            };
```

Try adding an `ev.stopPropagation()` in there and report back if this helps

**Comment by ElMaghri** [comment]
in svg.select.js i try to  ev.stopPropagation(); 
i have foun 2 section and not 3 
the first is 

           ` var curriedEvent = (function(k) {
                return function(ev) {
                    ev.stopPropagation();
                    console.log('ev.stopPropagation();');
                    ev = ev || window.event;
                    ev.preventDefault ? ev.preventDefault() : ev.returnValue = false;

                    var x = ev.pageX || ev.touches[0].pageX;
                    var y = ev.pageY || ev.touches[0].pageY;
                    _this.el.fire('point', { x: x, y: y, i: k, event: ev });
                };
`
and the second is 
`
//second section 
    function getMoseDownFunc(eventName) {
            return function(ev) {
                ev.stopPropagation();
                console.log('ajouter ev.stopPropagation()');
                ev = ev || window.event;
                ev.preventDefault ? ev.preventDefault() : ev.returnValue = false;

                var x = ev.pageX || ev.touches[0].pageX;
                var y = ev.pageY || ev.touches[0].pageY;
                _this.el.fire(eventName, { x: x, y: y, event: ev });
            };
        }

`

i added come console.log to test, but the problem still happened and i dont see any logs in my console

**Comment by Fuzzyma** [comment]
This one is missing: 

```js
            var curriedEvent = function (ev) {
                ev = ev || window.event;
                ev.preventDefault ? ev.preventDefault() : ev.returnValue = false;

                var x= ev.pageX || ev.touches[0].pageX;
                var y= ev.pageY || ev.touches[0].pageY;
                _this.el.fire('rot', {x: x, y: y, event: ev});
            };
```

**Comment by ElMaghri** [comment]
yay it's working thanks for your help 
i like to change the circles with rects in svg.select.js how can i do this

**Comment by ElMaghri** [comment]
yeah you are right thanks for you. it's working

**Comment by Fuzzyma** [comment]
Ok - we will then include this in the core. Release coming soon!

**Comment by Fuzzyma** [comment]
Released with svg.select.js v2.1.2
