### ISSUE TITLE
Polygon turns automatically to black

### ISSUE THREAD

**Issue by saintplay** [svgdotjs/svg.resize.js#39]
Hi!

So I'm using **svg.draggable.js** and **svg.resize.js** at the same time,
Also, I'm using exiting **polygons** in the DOM (I think, this is the cause of the issue)

https://jsfiddle.net/djap96/af4ssxjc/7/

I've notice these problems:

- The only way to get the resize working is using the **deepSelect** option, otherwise my polygon turns to black and the dragabillity doesn't work anymore
- Using the **depSelect** option just give me **4** dots when I expected **8**

Sorry if I'm missing something obvious and **Thank you!** for creating this awesome library, it already save me a bunch of headaches

**Comment by Fuzzyma** [comment]
There is a css file in the svg.select repo. You have to use it. Its there for a reason. You need it in order to have working resizing.

**Comment by saintplay** [comment]
It worked insanely good!

I didn't find information on how to use this library in a bundle-friendly environment like webpack.

So, I imported the library like this:

![image](https://user-images.githubusercontent.com/9372893/32417355-48f5e2c6-c226-11e7-92be-697848483049.png)

**Comment by Fuzzyma** [comment]
Unfortunately there isn't a better Way atm. Some day we have to love the whole system to a module system but since then it's a bit hakish.

**Comment by saintplay** [comment]
I'll close the issue, thanks
