### ISSUE TITLE
Weird behavior when resizing to the top or left

### ISSUE THREAD

**Issue by saintplay** [svgdotjs/svg.resize.js#40]
https://jsfiddle.net/djap96/7kmrf98b/

Resizing to the left or top is not precise.
I don't think this is an overall problem,

Maybe is the combination with other svg plugins,
check this jsfiddle and try by your own please,

**Comment by saintplay** [comment]
Can I get a hint here please, I tried disabling many things.
It turns out that the problem is the `snapToGrid` option.

This is a very important UX issue @Fuzzyma

Thanks in advance

**Comment by saintplay** [comment]
@maxmitti Thank you so much for fixing this problem, I drop a release on **npm** if you are interested

- https://www.npmjs.com/package/@4keys/svg.resize.js

Also, there is a similar problem when resizing using the polygon nodes

![image](https://user-images.githubusercontent.com/9372893/45259802-029dd100-b39b-11e8-9f3d-33112388c884.png)

- **Error Video** https://www.useloom.com/share/32f8bb91b7ae48ccaf11811c6f7f77c9

Do you know how to fix that?

**Comment by Fuzzyma** [comment]
I am a bit confused about all these issues because they are knew. If you look into teh demo page all this errors are not present: http://svgjs.com/svg.resize.js/demo/index.html

So they were introduced at some point

**Comment by maxmitti** [comment]
@Fuzzyma The issue is there too, but only when resizing beyond the border of the drawing.

**Comment by Fuzzyma** [comment]
ah okay, got it

**Comment by saintplay** [comment]
This is definitely fixed, thank you @maxmitti  @Fuzzyma
