### ISSUE TITLE
this.parent.set is not a function

### ISSUE THREAD

**Issue by notchris** [svgdotjs/svg.resize.js#53]
Using the latest version of svg.js and svg.resize.js

Following the example, I get `Uncaught TypeError: this.parent.set is not a function`

```
        let draw = SVG('#stage').size(window.innerWidth, window.innerHeight)
        let rect = draw.rect(100, 100).attr({ fill: '#f06' })
        rect.selectize().resize()
```

Thanks!

**Comment by notchris** [comment]
Oops sorry, this is a select issue!

**Comment by Byteschmiede** [comment]
Same here

**Comment by Fuzzyma** [comment]
https://github.com/svgdotjs/svg.select.js/issues/52
