### ISSUE TITLE
 How to keep the angles between the corners of the shape

### ISSUE THREAD

**Issue by hessam963** [svgdotjs/svg.resize.js#59]
hello
is there any way to keep the angles between the corners of the shape?
for example i draw a triangle with angles 45 45 90 ,when i resize it the degree between angles changes
how can i prevent from it?
thanks

**Comment by Fuzzyma** [comment]
You might want your own resize logic in that case

**Comment by hessam963** [comment]
> You might want your own resize logic in that case

yes
`shapeItem.selectize()
                    .resize({snapToGrid: 20,snapToAngle: 45, saveAspectRatio: true});`
is there option for it or ?

**Comment by Fuzzyma** [comment]
no there isnt. You can hook to the events of the select plugin and execute your own behavior
