### ISSUE TITLE
Resize element in svgjs v3.0 and 3.1

### ISSUE THREAD

**Issue by haizenbergD** [svgdotjs/svg.resize.js#65]
Hi, if there are any ways to resize elements with a mouse using svgjs v3.0 or 3.1?
I am using Angular and I was able to integrate draggable plugin.

Package.json
```
    "@svgdotjs/svg.js": "^3.0.16",
    "@svgdotjs/svg.draggable.js": "^3.0.2",
    "svg.resize.js": "1.4.3"
```
Component
```
import { ChangeDetectionStrategy, Component, ViewEncapsulation } from '@angular/core';
import { SVG } from '@svgdotjs/svg.js'
import "@svgdotjs/svg.draggable.js"
require('svg.resize.js') // this throws an error

@Component({
  selector: 'svg-comp',
  templateUrl: './markup.component.html',
  styleUrls: ['./markupcomponent.scss'],
})
export class SvgComponent {
  draw: any;
  ngAfterViewInit() {
    this.draw = SVG().addTo('#container').viewbox(0, 0, 300, 140);
    const rect = this.draw.rect(50, 50).fill('#f06')
    rect.draggable();
    // here i want to make component resizable
    rect.resizable();
  }
}
```

I think for `draggable` plugin it was solved by adding it to `@svgdotjs/svg.draggable.js`

**Comment by Nineswiss** [comment]
I am also looking for an answer to this.

**Comment by ProgrammerLrk** [comment]
Knock Knock, has the adaptation of version 3.x entered the schedule? Or should I stick with 2.7 in the short term

**Comment by Fuzzyma** [comment]
guess its time i sit myself down and finally do that :D

**Comment by Fuzzyma** [comment]
I guess that took 13h. svg.select.js and svg.resize.js are now available under the @svgdotjs namespace.
You can install them with `npm i @svgdotjs/svg.select.js @svgdotjs/svg.resize.js`.

Feedback is welcome. The api changed a little bit since I basically rewrote everything

**Comment by ProgrammerLrk** [comment]
@Fuzzyma ＼(＾▽＾)／ Thank you!
